[package]
name = "stlmunge"
version = "0.1.0"
authors = ["Cliff L. Biffle <code@cliffle.com>"]
edition = "2018"
workspace = ".."

[dependencies]
byteorder = "1.3.1"
ordered-float = { version = "2.0.1", default-features = false }
math = {path = "../math"}
